server {
    listen 80;

    location /dvwa/ {
        proxy_pass http://dvwa/;
    }

    location /webgoat/ {
        proxy_pass http://webgoat:8080/;
    }

    location /juice/ {
        proxy_pass http://juiceshop:3000/;
    }

    location /api/ {
        proxy_pass http://api-lab/;
    }
}